title: CSS Reference
subtitle: "CSS 属性可视化文档"
description: "CSS Reference is a  visual guide to CSS. It features the most popular properties, and explains them with illustrated and animated examples."
share: "CSS Reference: a visual guide to the most popular CSS properties."
url: http://blog.poetries.top/css-reference
markdown: kramdown
permalink: pretty
exclude: ['node_modules']
